
CREATE TABLE IF NOT EXISTS IC_INFO
(
    ID      INTEGER      NOT NULL AUTO_INCREMENT,
    IC_NAME VARCHAR(100) NOT NULL,
    IC_PATH VARCHAR(250) NOT NULL,
    IC_DESC VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS VC_INFO
(
    ID      INTEGER      NOT NULL AUTO_INCREMENT,
    VC_NAME VARCHAR(100) NOT NULL,
    VC_PATH VARCHAR(250) NOT NULL,
    VC_DESC VARCHAR(250)
);